// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as Atdgen_codec_runtime from "@ahrefs/bs-atdgen-codec-runtime/src/atdgen_codec_runtime.bs.js";

var partial_arg = Atdgen_codec_runtime.Encode[/* string */3];

var partial_arg$1 = Atdgen_codec_runtime.Encode[/* option_as_constr */23];

function write__1(param) {
  return partial_arg$1(partial_arg, param);
}

var read__1 = Atdgen_codec_runtime.Decode[/* option_as_constr */25](Atdgen_codec_runtime.Decode[/* string */7]);

var write_image = Atdgen_codec_runtime.Encode[/* make */0]((function (t) {
        return Atdgen_codec_runtime.Encode[/* obj */14](/* :: */[
                    Atdgen_codec_runtime.Encode[/* field */12](undefined, write__1, "url", t[/* url */0]),
                    /* :: */[
                      Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "attribution", t[/* attribution */1]),
                      /* :: */[
                        Atdgen_codec_runtime.Encode[/* field */12](undefined, write__1, "attributionUrl", t[/* attributionUrl */2]),
                        /* [] */0
                      ]
                    ]
                  ]);
      }));

var read_image = Atdgen_codec_runtime.Decode[/* make */0]((function (json) {
        var partial_arg = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$1 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$2 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$3 = Atdgen_codec_runtime.Decode[/* field */15];
        return /* record */[
                /* url */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg("url", read__1, param);
                      }), json),
                /* attribution */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$2("attribution", partial_arg$1, param);
                      }), json),
                /* attributionUrl */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$3("attributionUrl", read__1, param);
                      }), json)
              ];
      }));

var write_coordinates = Atdgen_codec_runtime.Encode[/* make */0]((function (t) {
        return Atdgen_codec_runtime.Encode[/* obj */14](/* :: */[
                    Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* float */4], "lat", t[/* lat */0]),
                    /* :: */[
                      Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* float */4], "lng", t[/* lng */1]),
                      /* [] */0
                    ]
                  ]);
      }));

var read_coordinates = Atdgen_codec_runtime.Decode[/* make */0]((function (json) {
        var partial_arg = Atdgen_codec_runtime.Decode[/* float */5];
        var partial_arg$1 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$2 = Atdgen_codec_runtime.Decode[/* float */5];
        var partial_arg$3 = Atdgen_codec_runtime.Decode[/* field */15];
        return /* record */[
                /* lat */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$1("lat", partial_arg, param);
                      }), json),
                /* lng */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$3("lng", partial_arg$2, param);
                      }), json)
              ];
      }));

var write_city = Atdgen_codec_runtime.Encode[/* make */0]((function (t) {
        return Atdgen_codec_runtime.Encode[/* obj */14](/* :: */[
                    Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "id", t[/* id */0]),
                    /* :: */[
                      Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "name", t[/* name */1]),
                      /* :: */[
                        Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "country", t[/* country */2]),
                        /* :: */[
                          Atdgen_codec_runtime.Encode[/* field */12](undefined, write_coordinates, "coordinates", t[/* coordinates */3]),
                          /* :: */[
                            Atdgen_codec_runtime.Encode[/* field */12](undefined, write_image, "image", t[/* image */4]),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]);
      }));

var read_city = Atdgen_codec_runtime.Decode[/* make */0]((function (json) {
        var partial_arg = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$1 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$2 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$3 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$4 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$5 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$6 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$7 = Atdgen_codec_runtime.Decode[/* field */15];
        return /* record */[
                /* id */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$1("id", partial_arg, param);
                      }), json),
                /* name */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$3("name", partial_arg$2, param);
                      }), json),
                /* country */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$5("country", partial_arg$4, param);
                      }), json),
                /* coordinates */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$6("coordinates", read_coordinates, param);
                      }), json),
                /* image */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$7("image", read_image, param);
                      }), json)
              ];
      }));

var partial_arg$2 = Atdgen_codec_runtime.Encode[/* array */9];

function write__2(param) {
  return partial_arg$2(write_city, param);
}

var partial_arg$3 = Atdgen_codec_runtime.Decode[/* array */12];

function read__2(param) {
  return partial_arg$3(read_city, param);
}

var partial_arg$4 = Atdgen_codec_runtime.Encode[/* option_as_constr */23];

function write__3(param) {
  return partial_arg$4(write__2, param);
}

var read__3 = Atdgen_codec_runtime.Decode[/* option_as_constr */25](read__2);

var read_cityArray = read__3;

var write_cityArray = write__3;

export {
  read_image ,
  write_image ,
  read_coordinates ,
  write_coordinates ,
  read_city ,
  write_city ,
  read_cityArray ,
  write_cityArray ,
  
}
/* read__1 Not a pure module */
