// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as MaterialUi_List from "@jsiebern/bs-material-ui/src/MaterialUi_List.bs.js";
import * as MaterialUi_Avatar from "@jsiebern/bs-material-ui/src/MaterialUi_Avatar.bs.js";
import * as MaterialUi_Button from "@jsiebern/bs-material-ui/src/MaterialUi_Button.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";
import * as MaterialUi_ListItem from "@jsiebern/bs-material-ui/src/MaterialUi_ListItem.bs.js";
import * as MaterialUi_ListItemText from "@jsiebern/bs-material-ui/src/MaterialUi_ListItemText.bs.js";
import * as MaterialUi_ListItemAvatar from "@jsiebern/bs-material-ui/src/MaterialUi_ListItemAvatar.bs.js";
import * as MaterialUi_ListItemSecondaryAction from "@jsiebern/bs-material-ui/src/MaterialUi_ListItemSecondaryAction.bs.js";

function CityList(Props) {
  var cities = Props.cities;
  var selected = Props.selected;
  var removeCity = Props.removeCity;
  if (cities !== undefined) {
    return React.createElement(MaterialUi_List.make, {
                children: Belt_Array.map(cities, (function (city) {
                        return React.createElement(MaterialUi_ListItem.make, {
                                    button: true,
                                    children: null,
                                    selected: city[/* name */1] === selected,
                                    onClick: (function (param) {
                                        return ReasonReactRouter.push(city[/* name */1]);
                                      }),
                                    key: city[/* id */0]
                                  }, React.createElement(MaterialUi_ListItemAvatar.make, {
                                        children: React.createElement(MaterialUi_Avatar.make, {
                                              src: Belt_Option.getWithDefault(city[/* image */4][/* url */0], "")
                                            })
                                      }), React.createElement(MaterialUi_ListItemText.make, {
                                        primary: city[/* name */1],
                                        secondary: city[/* country */2]
                                      }), React.createElement(MaterialUi_ListItemSecondaryAction.make, {
                                        children: React.createElement(MaterialUi_Button.make, {
                                              children: "X",
                                              color: /* Secondary */67972948,
                                              variant: /* Outlined */-28821822,
                                              onClick: (function (param) {
                                                  return Curry._1(removeCity, city);
                                                })
                                            })
                                      }));
                      }))
              });
  } else {
    return "You have not visited any cities yet. :-(";
  }
}

var make = CityList;

export {
  make ,
  
}
/* react Not a pure module */
