/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const CityMapBS = require('./CityMap.bs');

import {city as Data_t_city} from './Data_t.gen';

import {element as React_element} from '../src/shims/React.gen';

export const make: (_1:{ readonly cities?: Data_t_city[]; readonly selected: string }) => React_element = CityMapBS.make;
