/* TypeScript file generated by genType. */

// tslint:disable-next-line:interface-over-type-literal
export type image = {
  readonly url?: string; 
  readonly attribution: string; 
  readonly attributionUrl?: string
};

// tslint:disable-next-line:interface-over-type-literal
export type coordinates = { readonly lat: number; readonly lng: number };

// tslint:disable-next-line:interface-over-type-literal
export type city = {
  readonly id: string; 
  readonly name: string; 
  readonly country: string; 
  readonly coordinates: coordinates; 
  readonly image: image
};
