// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

Emotion.$$global("html, body, #root, #root > div", /* :: */[
      Emotion.margin(Emotion.px(0)),
      /* :: */[
        Emotion.padding(Emotion.px(0)),
        /* :: */[
          Emotion.width(Emotion.pct(100)),
          /* :: */[
            Emotion.height(Emotion.pct(100)),
            /* [] */0
          ]
        ]
      ]
    ]);

Emotion.$$global("*", /* :: */[
      Emotion.boxSizing(/* borderBox */9307263),
      /* :: */[
        Emotion.fontFamily("Roboto"),
        /* [] */0
      ]
    ]);

Emotion.$$global(".leaflet-container", /* :: */[
      Emotion.height(Emotion.pct(100)),
      /* :: */[
        Emotion.width(Emotion.pct(100)),
        /* [] */0
      ]
    ]);

Emotion.$$global(".leaflet-popup-content-wrapper", /* :: */[
      Emotion.borderRadius(Emotion.px(0)),
      /* [] */0
    ]);

export {
  
}
/*  Not a pure module */
