// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as React from "react";
import * as Emotion from "bs-emotion/src/Emotion.bs.js";
import * as MaterialUi_Grid from "@jsiebern/bs-material-ui/src/MaterialUi_Grid.bs.js";
import * as MaterialUi_AppBar from "@jsiebern/bs-material-ui/src/MaterialUi_AppBar.bs.js";
import * as MaterialUi_Drawer from "@jsiebern/bs-material-ui/src/MaterialUi_Drawer.bs.js";
import * as MaterialUi_Toolbar from "@jsiebern/bs-material-ui/src/MaterialUi_Toolbar.bs.js";
import * as MaterialUi_Typography from "@jsiebern/bs-material-ui/src/MaterialUi_Typography.bs.js";
import * as CitySearch$ReactTemplate from "./CitySearch.bs.js";

var toolbar = Emotion.css(undefined, /* [] */0);

var drawer = Emotion.css(undefined, /* :: */[
      Emotion.important(Emotion.position(/* relative */903134412)),
      /* [] */0
    ]);

var container = Emotion.css(undefined, /* :: */[
      Emotion.height(/* `calc */[
            -1044768619,
            /* tuple */[
              /* sub */5745024,
              Emotion.pct(100),
              Emotion.px(64)
            ]
          ]),
      /* [] */0
    ]);

var Style = /* module */[
  /* toolbar */toolbar,
  /* drawer */drawer,
  /* container */container
];

function Layout(Props) {
  var children = Props.children;
  var menu = Props.menu;
  var cityCallback = Props.cityCallback;
  return React.createElement("div", undefined, React.createElement(MaterialUi_AppBar.make, {
                  children: React.createElement(MaterialUi_Toolbar.make, {
                        children: React.createElement(MaterialUi_Grid.make, {
                              children: null,
                              container: true
                            }, React.createElement(MaterialUi_Grid.make, {
                                  children: React.createElement(MaterialUi_Typography.make, {
                                        children: "Map-O-Pedia",
                                        className: Emotion.css(undefined, /* :: */[
                                              Emotion.important(Emotion.color(/* `hex */[
                                                        5194459,
                                                        "fff"
                                                      ])),
                                              /* [] */0
                                            ]),
                                        variant: /* H6 */16110
                                      }),
                                  item: true,
                                  md: /* V9 */8
                                }), React.createElement(MaterialUi_Grid.make, {
                                  children: React.createElement(CitySearch$ReactTemplate.make, {
                                        addCity: cityCallback
                                      }),
                                  item: true,
                                  md: /* V3 */2
                                }))
                      }),
                  position: /* Static */982536398
                }), React.createElement(MaterialUi_Grid.make, {
                  children: null,
                  className: container,
                  container: true
                }, React.createElement(MaterialUi_Grid.make, {
                      children: React.createElement(MaterialUi_Drawer.make, {
                            anchor: /* Left */847852583,
                            children: menu,
                            className: drawer,
                            open_: true,
                            variant: /* Persistent */-156865929,
                            classes: /* :: */[
                              /* PaperAnchorLeft */Block.__(3, [drawer]),
                              /* [] */0
                            ]
                          }),
                      item: true,
                      md: /* V3 */2
                    }), React.createElement(MaterialUi_Grid.make, {
                      children: children,
                      item: true,
                      md: /* V9 */8
                    })));
}

var make = Layout;

export {
  Style ,
  make ,
  
}
/* toolbar Not a pure module */
